/*
  Modelo de tabela para solicitações de despesas de viagem no ERP (SQL Server).
  Uso:
  1) Executar no banco do ERP.
  2) Ajustar nomes/schema conforme padrão interno.
*/

IF OBJECT_ID('dbo.RM_DESPESAS_VIAGENS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.RM_DESPESAS_VIAGENS (
    REQUEST_ID UNIQUEIDENTIFIER NOT NULL
      CONSTRAINT PK_RM_DESPESAS_VIAGENS PRIMARY KEY
      CONSTRAINT DF_RM_DESPESAS_VIAGENS_REQUEST_ID DEFAULT NEWID(),
    IDEMPOTENCY_KEY NVARCHAR(120) NOT NULL,
    SOLICITANTE NVARCHAR(80) NOT NULL,
    TIPO_SOLICITACAO NVARCHAR(120) NOT NULL,
    ORIGEM NVARCHAR(255) NOT NULL,
    DESTINO NVARCHAR(255) NOT NULL,
    PERIODO_INICIO DATE NOT NULL,
    PERIODO_FIM DATE NOT NULL,
    KM_ESTIMADO DECIMAL(10, 1) NULL,
    CENTRO_CUSTO NVARCHAR(80) NULL,
    TOTAL_VALOR DECIMAL(18, 2) NOT NULL,
    STATUS_INTEGRACAO VARCHAR(20) NOT NULL,
    NUMERO_RM NVARCHAR(40) NULL,
    RETRY_COUNT INT NOT NULL
      CONSTRAINT DF_RM_DESPESAS_VIAGENS_RETRY DEFAULT 0,
    LAST_ERROR NVARCHAR(1000) NULL,
    ITENS_JSON NVARCHAR(MAX) NULL,
    RATEIO_JSON NVARCHAR(MAX) NULL,
    ANEXOS_JSON NVARCHAR(MAX) NULL,
    PAYLOAD_JSON NVARCHAR(MAX) NULL,
    CREATED_AT DATETIME2(3) NOT NULL
      CONSTRAINT DF_RM_DESPESAS_VIAGENS_CREATED_AT DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2(3) NOT NULL
      CONSTRAINT DF_RM_DESPESAS_VIAGENS_UPDATED_AT DEFAULT SYSUTCDATETIME(),
    INTEGRATED_AT DATETIME2(3) NULL,
    CONSTRAINT UQ_RM_DESPESAS_VIAGENS_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_RM_DESPESAS_VIAGENS_STATUS
      CHECK (STATUS_INTEGRACAO IN ('PENDENTE', 'ENVIADO', 'ERRO', 'INTEGRADO')),
    CONSTRAINT CK_RM_DESPESAS_VIAGENS_DATE_RANGE CHECK (PERIODO_FIM >= PERIODO_INICIO),
    CONSTRAINT CK_RM_DESPESAS_VIAGENS_PAYLOAD_JSON CHECK (PAYLOAD_JSON IS NULL OR ISJSON(PAYLOAD_JSON) = 1),
    CONSTRAINT CK_RM_DESPESAS_VIAGENS_ITENS_JSON CHECK (ITENS_JSON IS NULL OR ISJSON(ITENS_JSON) = 1),
    CONSTRAINT CK_RM_DESPESAS_VIAGENS_RATEIO_JSON CHECK (RATEIO_JSON IS NULL OR ISJSON(RATEIO_JSON) = 1),
    CONSTRAINT CK_RM_DESPESAS_VIAGENS_ANEXOS_JSON CHECK (ANEXOS_JSON IS NULL OR ISJSON(ANEXOS_JSON) = 1)
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_RM_DESPESAS_VIAGENS_STATUS_CREATED'
    AND object_id = OBJECT_ID('dbo.RM_DESPESAS_VIAGENS')
)
BEGIN
  CREATE INDEX IX_RM_DESPESAS_VIAGENS_STATUS_CREATED
    ON dbo.RM_DESPESAS_VIAGENS (STATUS_INTEGRACAO, CREATED_AT DESC);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_RM_DESPESAS_VIAGENS_NUMERO_RM'
    AND object_id = OBJECT_ID('dbo.RM_DESPESAS_VIAGENS')
)
BEGIN
  CREATE INDEX IX_RM_DESPESAS_VIAGENS_NUMERO_RM
    ON dbo.RM_DESPESAS_VIAGENS (NUMERO_RM);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_RM_DESPESAS_VIAGENS_SOLICITANTE'
    AND object_id = OBJECT_ID('dbo.RM_DESPESAS_VIAGENS')
)
BEGIN
  CREATE INDEX IX_RM_DESPESAS_VIAGENS_SOLICITANTE
    ON dbo.RM_DESPESAS_VIAGENS (SOLICITANTE, CREATED_AT DESC);
END;
GO
